version: '3.1'
services:
  identity_postgres:
    restart: always
    image: postgres:16-alpine
    ports:
      - '${IDENTITY_POSTGRES_PORT:-55432}:5432'
    environment:
      POSTGRES_USER: ${IDENTITY_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB:-identity}
    volumes:
      - ./volumes/identity_postgres:/var/lib/postgresql/data
  favorites_postgres:
    restart: always
    image: postgres:16-alpine
    ports:
      - '${FAVORITES_POSTGRES_PORT:-55433}:5432'
    environment:
      POSTGRES_USER: ${FAVORITES_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${FAVORITES_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${FAVORITES_POSTGRES_DB:-favorites}
    volumes:
      - ./volumes/favorites_postgres:/var/lib/postgresql/data
  library_mongo:
    restart: always
    image: mongo:6.0
    ports:
      - '${LIBRARY_MONGO_PORT:-57017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LIBRARY_MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${LIBRARY_MONGO_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${LIBRARY_MONGO_DB:-library}
    volumes:
      - ./volumes/library_mongo:/data/db
  identity_redis:
    restart: always
    image: redis:7.2.3
    ports:
      - "127.0.0.1:${IDENTITY_REDIS_PORT:-56379}:6379"
    volumes:
      - ./volumes/identity_redis:/data
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD:-guest}
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "${AMQP_PORT:-55672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-55673}:15672"
